// Code generated by the Encore v1.57.5 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-5ypku.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the 5ypku Encore application.
 */
export default class Client {
    public readonly budgeting: budgeting.ServiceClient
    public readonly config: config.ServiceClient
    public readonly domain: domain.ServiceClient
    public readonly frontend: frontend.ServiceClient
    public readonly mlgateway: mlgateway.ServiceClient
    public readonly optimizer: optimizer.ServiceClient
    public readonly orchestrator: orchestrator.ServiceClient
    public readonly pacer: pacer.ServiceClient
    public readonly segmentation: segmentation.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.budgeting = new budgeting.ServiceClient(base)
        this.config = new config.ServiceClient(base)
        this.domain = new domain.ServiceClient(base)
        this.frontend = new frontend.ServiceClient(base)
        this.mlgateway = new mlgateway.ServiceClient(base)
        this.optimizer = new optimizer.ServiceClient(base)
        this.orchestrator = new orchestrator.ServiceClient(base)
        this.pacer = new pacer.ServiceClient(base)
        this.segmentation = new segmentation.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

export namespace budgeting {
    export interface Budget {
        id: number
        "team_id": number
        "lever_id": number
        "period_start": string
        "period_end": string
        "configured_total": number
    }

    export interface BudgetsResponse {
        budgets: Budget[]
    }

    export interface GetConfiguredBudgetsParams {
        "team_id": number
        "period_start": string
        "period_end": string
    }

    export interface RecordSpendParams {
        "assignment_id": number
        "team_id": number
        "lever_id": number
        amount: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.GetConfiguredBudgets = this.GetConfiguredBudgets.bind(this)
            this.RecordSpend = this.RecordSpend.bind(this)
            this.SyncFromConfig = this.SyncFromConfig.bind(this)
        }

        /**
         * GetConfiguredBudgets returns budgets for a team within a time period.
         */
        public async GetConfiguredBudgets(params: GetConfiguredBudgetsParams): Promise<BudgetsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/budgeting/budgets/query`, JSON.stringify(params))
            return await resp.json() as BudgetsResponse
        }

        /**
         * RecordSpend records an observed spend event against a budget.
         */
        public async RecordSpend(params: RecordSpendParams): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/budgeting/spend`, JSON.stringify(params))
        }

        /**
         * SyncFromConfig pulls budget configs from the config service and upserts them locally.
         */
        public async SyncFromConfig(): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/budgeting/sync`)
        }
    }
}

export namespace config {
    export interface BudgetConfig {
        id: number
        "team_id": number
        "lever_id": number
        "period_start": string
        "period_end": string
        "configured_total": number
    }

    export interface CohortConfig {
        id: number
        name: string
        predicate: JSONValue
        "created_at": string
    }

    export interface CreateBudgetConfigParams {
        "team_id": number
        "lever_id": number
        "period_start": string
        "period_end": string
        "configured_total": number
    }

    export interface CreateCohortParams {
        name: string
        predicate: JSONValue
    }

    export interface CreateLeverParams {
        "team_id": number
        name: string
        description: string
        "eligibility_predicate": JSONValue
    }

    export interface CreateTeamParams {
        name: string
        "line_of_business": string
    }

    export interface Lever {
        id: number
        "team_id": number
        name: string
        description: string
        "eligibility_predicate": JSONValue
        "created_at": string
    }

    export interface ListBudgetConfigsParams {
        TeamID: number
    }

    export interface ListBudgetConfigsResponse {
        "budget_configs": BudgetConfig[]
    }

    export interface ListCohortsResponse {
        cohorts: CohortConfig[]
    }

    export interface ListLeversParams {
        TeamID: number
    }

    export interface ListLeversResponse {
        levers: Lever[]
    }

    export interface ListTeamsResponse {
        teams: Team[]
    }

    export interface Team {
        id: number
        name: string
        "line_of_business": string
        "created_at": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.CreateBudgetConfig = this.CreateBudgetConfig.bind(this)
            this.CreateCohort = this.CreateCohort.bind(this)
            this.CreateLever = this.CreateLever.bind(this)
            this.CreateTeam = this.CreateTeam.bind(this)
            this.GetCohort = this.GetCohort.bind(this)
            this.GetLever = this.GetLever.bind(this)
            this.GetTeam = this.GetTeam.bind(this)
            this.ListBudgetConfigs = this.ListBudgetConfigs.bind(this)
            this.ListCohorts = this.ListCohorts.bind(this)
            this.ListLevers = this.ListLevers.bind(this)
            this.ListTeams = this.ListTeams.bind(this)
        }

        public async CreateBudgetConfig(params: CreateBudgetConfigParams): Promise<BudgetConfig> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/config/budget-configs`, JSON.stringify(params))
            return await resp.json() as BudgetConfig
        }

        public async CreateCohort(params: CreateCohortParams): Promise<CohortConfig> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/config/cohorts`, JSON.stringify(params))
            return await resp.json() as CohortConfig
        }

        public async CreateLever(params: CreateLeverParams): Promise<Lever> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/config/levers`, JSON.stringify(params))
            return await resp.json() as Lever
        }

        public async CreateTeam(params: CreateTeamParams): Promise<Team> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/config/teams`, JSON.stringify(params))
            return await resp.json() as Team
        }

        public async GetCohort(id: number): Promise<CohortConfig> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/config/cohorts/${encodeURIComponent(id)}`)
            return await resp.json() as CohortConfig
        }

        public async GetLever(id: number): Promise<Lever> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/config/levers/${encodeURIComponent(id)}`)
            return await resp.json() as Lever
        }

        public async GetTeam(id: number): Promise<Team> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/config/teams/${encodeURIComponent(id)}`)
            return await resp.json() as Team
        }

        public async ListBudgetConfigs(params: ListBudgetConfigsParams): Promise<ListBudgetConfigsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "team_id": String(params.TeamID),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/config/budget-configs`, undefined, {query})
            return await resp.json() as ListBudgetConfigsResponse
        }

        public async ListCohorts(): Promise<ListCohortsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/config/cohorts`)
            return await resp.json() as ListCohortsResponse
        }

        public async ListLevers(params: ListLeversParams): Promise<ListLeversResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "team_id": String(params.TeamID),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/config/levers`, undefined, {query})
            return await resp.json() as ListLeversResponse
        }

        public async ListTeams(): Promise<ListTeamsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/config/teams`)
            return await resp.json() as ListTeamsResponse
        }
    }
}

export namespace domain {
    export interface AssignIncentiveParams {
        "run_id": number
        "user_id": number
        "lever_id": number
        "team_id": number
        "predicted_cost": number
        "predicted_roi": number
    }

    export interface AssignmentRecord {
        id: number
        "run_id": number
        "user_id": number
        "lever_id": number
        "team_id": number
        "predicted_cost": number
        "predicted_roi": number
        status: string
        "assigned_at": string
    }

    export interface ListAssignmentsParams {
        RunID: number
    }

    export interface ListAssignmentsResponse {
        assignments: AssignmentRecord[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.AssignIncentive = this.AssignIncentive.bind(this)
            this.ListAssignments = this.ListAssignments.bind(this)
        }

        /**
         * AssignIncentive records an assignment and publishes spend.
         */
        public async AssignIncentive(params: AssignIncentiveParams): Promise<AssignmentRecord> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/domain/assign`, JSON.stringify(params))
            return await resp.json() as AssignmentRecord
        }

        public async ListAssignments(params: ListAssignmentsParams): Promise<ListAssignmentsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "run_id": String(params.RunID),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/domain/assignments`, undefined, {query})
            return await resp.json() as ListAssignmentsResponse
        }
    }
}

/**
 * Service frontend serves the TAROT Configuration UI.
 */
export namespace frontend {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.Index = this.Index.bind(this)
        }

        /**
         * Serves the frontend at the root URL.
         */
        public async Index(method: string, path: string[], body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/${path.map(encodeURIComponent).join("/")}`, body, options)
        }
    }
}

export namespace mlgateway {
    export interface Opportunity {
        "user_id": number
        "lever_id": number
    }

    export interface Prediction {
        "user_id": number
        "lever_id": number
        "predicted_cost": number
        "predicted_roi": number
        "uplift_vector": JSONValue
    }

    export interface ScoreRequest {
        "run_id": number
        opportunities: Opportunity[]
    }

    export interface ScoreResponse {
        predictions: Prediction[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ScoreOpportunities = this.ScoreOpportunities.bind(this)
        }

        /**
         * ScoreOpportunities generates predictions for a batch of (user, lever) pairs.
         * Uses synthetic deterministic scoring and persists results for audit.
         */
        public async ScoreOpportunities(params: ScoreRequest): Promise<ScoreResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/mlgateway/score`, JSON.stringify(params))
            return await resp.json() as ScoreResponse
        }
    }
}

export namespace optimizer {
    export interface Assignment {
        "user_id": number
        "lever_id": number
        "predicted_cost": number
        "predicted_roi": number
    }

    export interface Candidate {
        "user_id": number
        "lever_id": number
        "predicted_cost": number
        "predicted_roi": number
    }

    export interface LeverBudget {
        "lever_id": number
        available: number
    }

    export interface SolveRequest {
        "run_id": number
        candidates: Candidate[]
        "lever_budgets": LeverBudget[]
    }

    export interface SolveResponse {
        assignments: Assignment[]
        "total_cost": number
        "total_roi": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.Solve = this.Solve.bind(this)
        }

        /**
         * Solve runs the MKP optimizer on the given candidates and budget constraints.
         */
        public async Solve(params: SolveRequest): Promise<SolveResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/optimizer/solve`, JSON.stringify(params))
            return await resp.json() as SolveResponse
        }
    }
}

export namespace orchestrator {
    export interface RunStatus {
        id: number
        "team_id": number
        "cohort_id": number
        status: string
        "started_at": string
        "finished_at": string
        error: string
        steps: RunStep[]
    }

    export interface RunStep {
        step: string
        status: string
        "started_at": string
        "finished_at": string
    }

    export interface TriggerRunParams {
        "team_id": number
        "cohort_id": number
    }

    export interface TriggerRunResponse {
        "run_id": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.GetRunStatus = this.GetRunStatus.bind(this)
            this.TriggerRun = this.TriggerRun.bind(this)
        }

        /**
         * GetRunStatus returns the status and steps of a targeting run.
         */
        public async GetRunStatus(id: number): Promise<RunStatus> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/orchestrator/runs/${encodeURIComponent(id)}`)
            return await resp.json() as RunStatus
        }

        /**
         * TriggerRun initiates a new targeting run for a team and cohort.
         */
        public async TriggerRun(params: TriggerRunParams): Promise<TriggerRunResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/orchestrator/runs`, JSON.stringify(params))
            return await resp.json() as TriggerRunResponse
        }
    }
}

export namespace pacer {
    export interface BudgetCap {
        "team_id": number
        "lever_id": number
        available: number
        configured: number
        observed: number
        "predicted_liability": number
    }

    export interface GetAvailableBudgetParams {
        "team_id": number
        "period_start": string
        "period_end": string
    }

    export interface GetAvailableBudgetResponse {
        caps: BudgetCap[]
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.GetAvailableBudget = this.GetAvailableBudget.bind(this)
        }

        /**
         * GetAvailableBudget computes available budget per lever for the current run.
         * Formula: available = max(0, configured - observed - liability)
         */
        public async GetAvailableBudget(params: GetAvailableBudgetParams): Promise<GetAvailableBudgetResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/pacer/available`, JSON.stringify(params))
            return await resp.json() as GetAvailableBudgetResponse
        }
    }
}

export namespace segmentation {
    export interface CreateUserParams {
        name: string
        "segment_attrs": JSONValue
    }

    export interface GetEligibleUsersResponse {
        users: User[]
    }

    export interface ListUsersResponse {
        users: User[]
    }

    export interface User {
        id: number
        name: string
        "segment_attrs": JSONValue
        "created_at": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.CreateUser = this.CreateUser.bind(this)
            this.GetEligibleUsers = this.GetEligibleUsers.bind(this)
            this.ListUsers = this.ListUsers.bind(this)
        }

        public async CreateUser(params: CreateUserParams): Promise<User> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/segmentation/users`, JSON.stringify(params))
            return await resp.json() as User
        }

        /**
         * GetEligibleUsers resolves a cohort predicate into matching users using JSONB containment.
         */
        public async GetEligibleUsers(cohortID: number): Promise<GetEligibleUsersResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/segmentation/cohorts/${encodeURIComponent(cohortID)}/users`)
            return await resp.json() as GetEligibleUsersResponse
        }

        public async ListUsers(): Promise<ListUsersResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/segmentation/users`)
            return await resp.json() as ListUsersResponse
        }
    }
}

// JSONValue represents an arbitrary JSON value.
export type JSONValue = string | number | boolean | null | JSONValue[] | {[key: string]: JSONValue}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "5ypku-Generated-TS-Client (Encore/v1.57.5)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
